### ISSUE TITLE
client server

### ISSUE THREAD

**Issue by atv2016** [chenxiaoqino/udp-image-streaming#2]
I noticed when i start a server on one pc, and a client on the other, the client will setup a camera as if it is a server itself. It won't actually receive the server feed. It works fine on the same pc.

I'll have to experiment with this a bit more but it seems to not completely work as it should yet.

**Comment by chenxiaoqino** [comment]
Note that it's the client sending the images to the server, not the other
way.
(For UDP, it's easier for client to push new data to server.)

## 

Xiaoqi, sent from phone

**Comment by atv2016** [comment]
Hi Chenxiaoqino,
Ah ok - i'm not used to that logic.I always think of client as receiving and server as sending.
So if i want a group of 10 pc's to receive one camera from another pc.

I would run server on the group of pc's.
and i would need 10 instances of client to 10 different ip addresses on the camera pc.
I'll try that.

**Comment by chenxiaoqino** [comment]
Ah, yes, but probably there'll be better way to do that. The camera machine
should do an Anycast to 10 PCs?

## 

Xiaoqi, sent from phone

**Comment by atv2016** [comment]
I was just talking about my understanding of the client server setup.

But yes for group videoconferencing multicast (not anycast that's different, used in BGP) would be most bandwidth efficient.

But multicast is generally only suitable for enterprise deployments where you have a switch that's igmp snooping capable. If you try to run multicast at home, you will usually flood your network. I know from experience :-)

But yes multicast in addition would definitely be nice to have. 

Did you see my other issue post in regards to some other topics?

Thanks Chen!

**Comment by chenxiaoqino** [comment]
Yes; the latency is negligible in the algorithm part when the CPU is not overloaded, but it is difficult to measure (possibly by adding timestamps to packet?) Meanwhile, I believe UDP already achieved low latency compared to TCP.

For other features, it's important to keep in mind that industry-scale video streaming protocols, which includes many features, typically also incurs a much larger latency (even due to codecs alone); you may refer to [SRS](https://github.com/ossrs/srs) for a low-latency video streaming framework.

If latency is tolerable, It's possible to achieve similar streaming using `ffmpeg`. Please share your email and we can discuss them in more detail.

**Comment by atv2016** [comment]
my emailaddress is alefveld@outlook.com
