### ISSUE TITLE
configurations

### ISSUE THREAD

**Issue by landauron** [chenxiaoqino/udp-image-streaming#4]
Hello chenxiaoqino,

I want to use your code in a new project (credit will be given) but i have problem with the configurations, do you have a summery of all the VS configurations changes need to be done for running the code or something like this? it will be very helpful.

Thank you!
ron

**Comment by chenxiaoqino** [comment]
By VS did you mean Visual Studio?

## 

Xiaoqi, sent from phone

**Comment by landauron** [comment]
yes

**Comment by chenxiaoqino** [comment]
It should be no more than configuring both dependencies (OpenCV and the network lib). 

I can try it out and make screenshots if necessary, but it'll be nice if you can try it first!

Side note: OpenCV configuration in VS is a little bit tricky, you may try to follow the official guide at [here](http://docs.opencv.org/2.4/doc/tutorials/introduction/windows_visual_studio_Opencv/windows_visual_studio_Opencv.html) or [there](http://docs.opencv.org/2.4/doc/tutorials/introduction/windows_install/windows_install.html). If the test code complies successfully, then probably this project too. (You may want to compile Client and Server separately since compiling both in one VS project is even more tricky...)

**Comment by landauron** [comment]
i am working with open cv so i have no problem with the open cv configuration, and i succeed to compile both the client and the server with your solution, ill try to copy the configurations from your project. thanks.

**Comment by chenxiaoqino** [comment]
I hope you can also work no problem with the networking part! Make sure you
test on the same machine first. :-)

## 

Xiaoqi, sent from phone

**Comment by landauron** [comment]
it is working and kicks ass. thanks

**Comment by chenxiaoqino** [comment]
Great to hear that!!! Don't forget to let us know the link when your
awesome project is ready :-P

## 

Xiaoqi, sent from phone
