### ISSUE TITLE
Unexpected size pack

### ISSUE THREAD

**Issue by ejwolfe** [chenxiaoqino/udp-image-streaming#8]
I'm trying to stream from one computer to another but keep receiving the unexpected size pack. Using my pc as the client and my laptop as the server, I get will get messages like this:

```
expecting length of packs:19
Received unexpected size pack:4
Received unexpected size pack:4
Received unexpected size pack:4
Received packet from 192.168.1.2:42113
Corrupt JPEG data: premature end of data segment
```

Doing the opposite configuration with the pc as the server and my laptop as the client, I do not receive this error. 

Could the webcam on the pc be sending too much data to the laptop? If so, how can the code be changed to account for this?

**Comment by chenxiaoqino** [comment]
According to the error message, most actual data packets (length~=1024) are
dropped and only the header packets (length=4) are delivered. Meanwhile,
the data packets are occasionally delivered.

I do not believe it's due to too much data being sent, since the bandwidth
between your desktop and laptop is probably symmetric, and it's unlikely
that the flow on one direction can exhaust the link while the flow on the
other direction works well. It's possible that firewall , MTU, or other
network issue prevented the delivery of large UDP packets; I don't think
it's because there's too much data. However, if you really want to try it,
you can change the JPEG encoding compression quality factor to shrink the
stream data. The quality factor is in config.h. Changing the size of frame
can also reduce the amount of data per frame.

You can use Netcat with option -u to debug UDP packet issue.
